### ISSUE TITLE
Jon Snow not entirely crawled

### ISSUE THREAD

**Issue by marcusnovotny** [Rostlab/JS16_ProjectD_Group4#103]
In the newest implementation, the mobile js crawler only crawled our most popular character Jon Snow post October 2015. Restarting didn't change anything. Did anybody experience the same?

**Comment by julienschmidt** [comment]
Try lowering the threshold in crawler/mobile.js and use `gotsent.updateCharacter("<Jon Snows' id>")` in example/app again and again until it works. Twitter is really moody. I guess it depends on the cache of the server handling your request.

**Comment by marcusnovotny** [comment]
Will try! I also noticed completely new characters getting crawled in the 4th or 5th run already. Is that the same issue?

**Comment by julienschmidt** [comment]
I have no idea what you mean. Logs?

**Comment by marcusnovotny** [comment]
For example, currently the crawler is crawling the complete history of Viserys Targaryen for the last 5 years even though it has been running multiple iterations already.

**Comment by julienschmidt** [comment]
... logs?

**Comment by marcusnovotny** [comment]
Which directory?

**Comment by julienschmidt** [comment]
your shell

**Comment by marcusnovotny** [comment]
I don't know where to get those from

**Comment by julienschmidt** [comment]
![screen shot 2016-03-30 at 21 33 16](https://cloud.githubusercontent.com/assets/944947/14154844/0e266b2c-f6bf-11e5-97f8-fe2c832127fc.png)
That kind of output

**Comment by julienschmidt** [comment]
If it says inserted: > 0, then the crawler found new tweets. Otherwise it should abort, unless you set the full flag in update / updateCharacter (not set in the update loop).

**Comment by marcusnovotny** [comment]
Yeah it found new tweets, but I thought it finds them in the first full crawl and then only updates the ones which were tweeted in the meantime. I guess I have a wrong idea of how it works

**Comment by julienschmidt** [comment]
If Twitter wasn't weird, then yes.

**Comment by marcusnovotny** [comment]
Classic Twitter
![](http://i.huffpost.com/gen/1143173/thumbs/o-POTOO-FUNNY-BIRD-570.jpg?6)

**Comment by marcusnovotny** [comment]
I'm worried. This is happening for a lot of the very major characters of the show. I only have 2015+ data for:
- Arya Stark
- Sansa Stark
- Daenerys Targaryen
- Jon Snow
- Jaime Lannister
- Cersei Lannister
- Theon Greyjoy

I tried crawling Jon Snow repeatedly but had no luck either
![](http://i.imgur.com/SJw5ZrZ.png)

Just checked my old csv data, had Jon Snow there from 2007 on but not the others. 

@julienschmidt @santanumohanta Can you check whether you have more data on these characters?

If not: Is there a workaround?

**Comment by julienschmidt** [comment]
Lower the threshold and recrawl with either `gotsent.update(true)` or `gotsent.updateCharacter(id, true)` for the specific characters.
Twitter sucks. End of story.

**Comment by julienschmidt** [comment]
Is still have 2 older DB dumps, we could try to merge them together and also provide that new DB dump to group F / @sacdallago.
Fortunately we only need to crawl the old tweets once.
