### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectD_Group4#107]
@CavidSalahov 
I still get this error, I think it comes from your plugin. The config file is fully filled.
`[main][ERROR] { status: 503,
  data: '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>503 Service Unavailable</title>\n</head><body>\n<h1>Service Unavailable</h1>\n<p>The server is temporarily unable to service your\nrequest due to maintenance downtime or capacity\nproblems. Please try again later.</p>\n<p>Additionally, a 503 Service Unavailable\nerror was encountered while trying to use an ErrorDocument to handle the request.</p>\n</body></html>\n' }`
`[main][ERROR] { status: 503,
  data: '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>503 Service Unavailable</title>\n</head><body>\n<h1>Service Unavailable</h1>\n<p>The server is temporarily unable to service your\nrequest due to maintenance downtime or capacity\nproblems. Please try again later.</p>\n<p>Additionally, a 503 Service Unavailable\nerror was encountered while trying to use an ErrorDocument to handle the request.</p>\n</body></html>\n' }
`
After that message:
`[core/db][INFO] connected.
`

**Comment by julienschmidt** [comment]
Yep, that's our plugin.
Version 0.2.0 still contains the old API URL. Please overwrite it by adding

``` js
"api": {
        "https": true,
        "host": "api.got.show",
        "prefix": "/api/"
    },
```

To the config. Alternatively you can directly use `gotsent.cfg.api.host = "api.got.show`.

**Comment by yashha** [comment]
Thanks! :)
It doesn't show up in your docs so I thought I can remove it.
https://www.npmjs.com/package/gotsentimental
Please update :)

**Comment by julienschmidt** [comment]
Our final deadline is today, so we will publish another version later. In our repository it is already fixed.
