### ISSUE TITLE
Revert master to initial state

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectD_Group4#11]
Hey Julien, I just checked master and saw it was not in the cb4f4d09b04ec460d2c1fc16e08e2d4919213c5a state. Could you revert your commit?

Thx

**Comment by julienschmidt** [comment]
I tried already, but the master branch is protected. I can't do a forced push.

**Comment by sacdallago** [comment]
Try now and close the issue when you are done so I protect it again (tell no one :D)

**Comment by julienschmidt** [comment]
@sacdallago I need to force push again :blush:

**Comment by sacdallago** [comment]
Guys, pay attention to this pls

P.S.: same as above, close when done
