### ISSUE TITLE
Keeping @sacdallago busy

### ISSUE THREAD

**Issue by marcusnovotny** [Rostlab/JS16_ProjectD_Group4#116]
Remember to upload the new version @sacdallago :wink:

**Comment by julienschmidt** [comment]
But optimally you wait until the first crawl iteration is done. Otherwise you'll lose some tweets

**Comment by sacdallago** [comment]
When will that be? :laughing:

**Comment by julienschmidt** [comment]
Around 16 hours after you you started the app :p
If you can find the word "scheduling" in the console output, it is trying to schedule the next iteration

**Comment by sacdallago** [comment]
So I'll wait tomorrow

**Comment by sacdallago** [comment]
I fucked up something, so I had to restart :D too bad
