### ISSUE TITLE
Visualization Fixes

### ISSUE THREAD

**Issue by marcusnovotny** [Rostlab/JS16_ProjectD_Group4#117]
Main issues
<s>\- Fix Dates to align with Eastern Time </s> Changed timezone to UTC
<s>\- Fix Touch Interaction with Buttons</s> Done!
<s>\- Zooming buttons (for single touchpads)</s> can't manage in time for the deadline
<s>\- Limit domain to available data if less than a few months</s> Done!

<s>Minor issues</s> Skipped due to missing time
<s>\- Add clicking functionality to scrollbar, make it align with mouse / touch gesture
- Rename trendline (in ________________ )</s>

<s>\- Redesign Score / Day (Hour) so it doesn't look like a button</s> Done!

**Comment by julienschmidt** [comment]
Regarding scrollbar: Yes keep the plot behavior as it is.

However users have certain expectations how different UI elements work. The indicator of a scrollbar should follow the mouse / finger, everything else is unexpected and might seem unresponsive / slow. And it should jump to the position if one clicks somewhere else on the bar.

**Comment by marcusnovotny** [comment]
That is a great idea. Haven't thought about clicking. I'll add it to the major issues. Hopefully I get it all done!

**Comment by julienschmidt** [comment]
That is a minor issue :)
