### ISSUE TITLE
Adding new items to our crawler list

### ISSUE THREAD

**Issue by marcusnovotny** [Rostlab/JS16_ProjectD_Group4#118]
Hey there!

A question for @julienschmidt - can we just add new items to the list of characters we crawl without disturbing the other projects? "House Stark", "House Lannister" and "George RR Martin" would be really cool to have for the landing pages

**Comment by julienschmidt** [comment]
Hey there!

An answer for @marcusnovotny - there is obviously no exported function for it (yet), but you could just use [Character.addIfNotExists](https://github.com/Rostlab/JS16_ProjectD_Group4/blob/develop/models/character.js#L37) to add a character with `{ name: "House Stark", slug: "House_Stark" }` etc. So yes, it is possible.

**Comment by marcusnovotny** [comment]
Haha! Thanks for the quick reply. The link was just what I needed.
