### ISSUE TITLE
MouseDrag in chart

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectD_Group4#120]
When draging the mouse and there are two charts on one page the last initialized chart is being changed
And the background lines of the first chart are moving.

**Comment by marcusnovotny** [comment]
@yashha I fixed your issues but those were really tiny fixes and I don't think it's not worth making a new version already. Just swap out the public/chart.js for now.

[chartjs.zip](https://github.com/Rostlab/JS16_ProjectD_Group4/files/204449/chartjs.zip)

I've found a way to get the missing tweets, which solves the original problem with the too large date range. I can give you a complete db on Friday and then we'll update you to the latest version. Ok? Also relevant for @CavidSalahov I think

**Comment by yashha** [comment]
Important would be to set the startdate to the oldest tweet or a bit before that :)
It is not like that at the moment 
Edit: at least not always :) 
It would be also nice that the legend would be always visible like toggle trendline button. With transparency when not hovering.

**Comment by marcusnovotny** [comment]
It currently displays 2014 - today if there's less than three months of data available. Will try something else.

What would you prefer? Legend always visible or "Love" and "Hate" next to the y axis like Tatyana suggested? The legend is pretty big, I don't wanna crowd the graph more than necessary

**Comment by yashha** [comment]
Tatyana's suggestion is fine, too. :)
