### ISSUE TITLE
No more Yellow Dick

### ISSUE THREAD

**Issue by marcusnovotny** [Rostlab/JS16_ProjectD_Group4#125]
Yellow Dick is apparently still lingering in the got show database. We'll have to manually remove him with db.charactersentiments.remove({"name": "Yellow Dick"}) so he doesn't show up in the statistics :laughing:

**Comment by sacdallago** [comment]
Oh sorry. Done. Also showing some additional info you might be interested in :D

``` bash
> db.charactersentiments.remove({"name": "Yellow Dick"})
WriteResult({ "nRemoved" : 1 })
> show dbs
gotsentimental  3.952GB
```
