### ISSUE TITLE
Make seasons visible on full zoom out

### ISSUE THREAD

**Issue by marcusnovotny** [Rostlab/JS16_ProjectD_Group4#128]
Hey @sacdallago @yashha 

Can you please pull the latest changes from pull request #127 ? I noticed the got.show antagonist feature doesn't show the season labels when zooming out even though there's enough space so I adjusted them to show for widths > 400. It's just a 1 line change

**Comment by sacdallago** [comment]
I did! You mean I got to `npm update` right? I did that like.. 2 days ago

**Comment by marcusnovotny** [comment]
No I only changed the public/chart.js file here, there was no update to the package. Can you just git pull the changes?

got.show still loads the old one: https://got.show/d4/chart.js
This is the new one:  https://github.com/Rostlab/JS16_ProjectD_Group4/blob/develop/public/chart.js

Only a change in line 760. 

} else if (w > 500 || dmn < (3 \* 365 \* 86400000)) { //Show season start

to 

} else if (w > **400** || dmn < (3 \* 365 \* 86400000)) { //Show season start

**Comment by sacdallago** [comment]
?????

I have no idea where I should do the change and it sounds a lot to me like this is not the way this needs to be done.

If you made a change to your application, please package it and load the latest version on NPM. I'll then `npm update`. If this file is independent from the package, please find in project F where the file is, change the line, open a PR and put me as assignee

**Comment by marcusnovotny** [comment]
The file is part of the package, but that one line change is only relevant for our website. It shows the Season labels also for a little less wide graphs when zooming out completely. Basically a special adaption because the Twitter graphs on the homepage are not as wide as expected.

That change is irrelevant for other users of the package. Updating it because of that one line seems like a huge overkill regarding the fact it's been [downloaded 1600 times already.](https://www.npmjs.com/package/gotsentimental)

What's the best practice in your opinion? Update the whole package or simply make that one line change in our version?

**Comment by sacdallago** [comment]
There's nothing wrong with updating the package for one line :) And I can still not understand what you are talking about. If this is happening in project F, and project F is using code coming from your package, then I shouldn't be forced to update the line of code myself in the `node_packages` folder, the package should get updated and that line should be there in the update :)

**Comment by marcusnovotny** [comment]
Ok, @CavidSalahov can you update the package?

**Comment by jsalahov** [comment]
Yup. Done :smiley:

**Comment by sacdallago** [comment]
Everything should be updated
