### ISSUE TITLE
CSV files too larget for the server

### ISSUE THREAD

**Issue by goldbergtatyana** [Rostlab/JS16_ProjectD_Group4#129]
@julienschmidt @marcusnovotny guys, we have an EMERGENCY. We really need your HELP!

The site keeps getting down and the servers are 100% full. Is there a way for storing the files somewhere else?

**Comment by julienschmidt** [comment]
The CSV files are too large?

What is the current size of the folder and how many files are there?

I'd rather suspect that there is something wrong.

**Comment by goldbergtatyana** [comment]
Christian says that he agrees, that there is something eating up memory. There are too many connections to check if there is an attack. He says he's running out of time and options.. :(

**Comment by julienschmidt** [comment]
If there are too many connections, it is more likely that something doesn't scale well.

Our module is completely independent of the number of connections, it just generates static files + updates the DB.
You can temporarily remove the [startUpdateLoop call](https://github.com/Rostlab/JS16_ProjectF/blob/2859ed087b7a292b1e6b504921f554e55cda7a4c/server/d4.js#L38) and see if that helps.

I'd however check other caches, log files etc first.

**Comment by sacdallago** [comment]
Solved guys. Thx.

I'm melting (as much as the server)
