### ISSUE TITLE
Share schema definition with project A and use same database

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectD_Group4#20]
In an effort to bring together the pieces, we came up with the following requirements:

The schema of what you store about the sentiments of a character needs to be merged with the database of project A.

This can be done in the following fashion:

```
{
  name: "Some character",
  ...,
  D5: {
     // D5's schema here
  },
  D4: {
     // YOUR TWITTER SCHEMA HERE
  }
}
```

Where I mean [this](https://github.com/Rostlab/JS16_ProjectD_Group4/blob/develop/models/tweet.js#L8) by your twitter schema.

You will write directly on the database that **A** uses that should be somewhere on mLab. If @kordianbruck is using his own server to store the data, please come up with some idea.. I understand that you are not keen on having an API over mutable data, but until 1 day ago you could get DDosed.. so.. you know :dancer:

@AlexMoroz I assigned the issue to you because **E** should supervise this, but defer commitment to one of your teammates.

**Comment by AlexMoroz** [comment]
@CavidSalahov assign it to yourself =)
I don't have access to the repo.

**Comment by julienschmidt** [comment]
I'm a mongoDB newb but is it a good idea to embed millions of tweets in another document? 
Also we need to store the [popularity](https://github.com/Rostlab/JS16_ProjectD_Group4/blob/develop/models/character.js#L20) somewhere in the character schema

**Comment by sacdallago** [comment]
Sorry. Yes. It's the popularity that you will store in the characters schema of A. The tweets you can save on a gitignored folder on FS or a supplementary dummy database (even SQLisch, no F given in that sense :D ). Storing this kind of data in a production database, as you say, makes no sense.
I mean; I would do it like this! Then, do as you see fit.

**Comment by jsalahov** [comment]
Why this is assigned to Project E? I wasn't present on Tuesday's meeting. If there are some new responsibilities, it would be nice if someone would brief me :smile:

**Comment by kordianbruck** [comment]
@CavidSalahov instead of using your own database it would be smart to use one database when we merge all the projects together. So we have to integrate your schema now, in order that packaging becomes easier later.

**Comment by jsalahov** [comment]
Thanks @kordianbruck, I thought that was the plan from the get-go. Still @sacdallago why this is assigned to E? :confused:

**Comment by sacdallago** [comment]
@CavidSalahov Your team provides integration, I cite the wiki's title:

> #### Project E
> 
> Title: Integration

:D just _thought_ this would need some attention by someone who has an overview of integration, ya know :P

**Comment by julienschmidt** [comment]
[WIP]

```
{
  name: "Some character",

  // slug for character (unique ID for URL generated from name)
  slug: {type: String, required: true, unique: true},

  ...,
  D4: {
    // total number of tweets
    tweets: {type: Number, default: 0},

    // total number of positive tweets
    positive: {type: Number, default: 0},

    // total number of negative tweets
    negative: {type: Number, default: 0},

    // how much is this character discussed lately?
    heat: {type: Number, default: 0},

    // how popular (liked) is this character lately?
    popularity: {type: Number, default: 0},

    // when was the sentiment data last updated?
    updated: {type: Date}
  }
}
```

anything to add?

**Comment by julienschmidt** [comment]
Project A probably also should add [a slug](https://github.com/Rostlab/JS16_ProjectD_Group4/blob/f7f15887322cbb6574549bad003b91292cdcf1e3/models/character.js#L12) to characters, so that they are consistent between all projects.

**Comment by julienschmidt** [comment]
Slug Issue: https://github.com/Rostlab/JS16_ProjectA/issues/100

**Comment by julienschmidt** [comment]
@sacdallago just to clarify once again: In the original issue description you said "_You will write directly on the database that A uses that should be somewhere on mLab_".
But later you told us (in person) that we only provide them with a schema for the data they can fetch from our package and an JS API func to get this data. We do not update the DB directly. Is that correct?

**Comment by AlexMoroz** [comment]
@julienschmidt  On the presentation on Thursday it was decided that project D will use API. And it will be integrated in project F, so there is no possibility to use DB directly.

**Comment by AlexMoroz** [comment]
Also I thought that you had feature freeze on 21st, or no?

**Comment by julienschmidt** [comment]
But do they still require our Schema? They could just use our JS API :wink: (we have this information in our DB anyway)

And regarding feature freeze: https://groups.google.com/forum/#!topic/javascript-technology-2016/P7Vo_NJcDXY
March 28 for Project D. But I'll try to finish tomorrow. I'm already using the time that I should spent on my thesis for this project...

**Comment by sacdallago** [comment]
@julienschmidt they don't require your schema, that's correct. You are aware as well as I that things in this project have changed unexpectedly :( I'm very sorry for the development, I truly am, I've just been trying to make sense out of the different components there were and sometimes it meant sending you directions which ultimately produced superfluous outcomes.
You know your project best and I believe you are right.
