### ISSUE TITLE
Database for tweets

### ISSUE THREAD

**Issue by kajo404** [Rostlab/JS16_ProjectD_Group4#21]
Hello Guys,

this is to start the discussion about the tweet database that stores all tweets gathered. I still think it is a good idea to use the same database for both our groups to increase sample size. 

Now we need to figure out what database to use and what information we want to store. I took a look at your schema you used for mongodb and we have nothing to add, it seems to cover all the information needed. (We can drop some information though)

Happy to hear your thoughts on this.

**Comment by kajo404** [comment]
Okay so we petty much settled on using mongoDB for this. I guess we can make a generell schema that saves all the important information about a tweet. We can include a optional sentiment field where you can put in your groups sentiment score. You can then find the tweets we collected and run your sentiment analysis aswell and fill the information to fit your needs.

**Comment by julienschmidt** [comment]
Not that many differences anymore :stuck_out_tongue_winking_eye: 
https://github.com/Rostlab/JS16_ProjectD_Group5/commit/307d723c52f5e4815c56acefc9b5292347d2ec34#diff-6683268f1fdd0443cb8c62f4ac6ee4fcR5

**Comment by julienschmidt** [comment]
Sorry @kajo404 but I think we are unable to use a common database because a) the latency is too high (the crawling already takes way too long) b) Free solutions are too limited (DB size / #requests).

However, we are able to crawl the whole Twitter archive now. We can provide you with a dump of our database, if you need one.

**Comment by sacdallago** [comment]
What do you use again for the tweets? Mongo, right?
How big do you expect the database to be? And prospective growth in 1y?

@gyachdav we might need to bother someone again.

I'm gonna be out for the day. If anything comes up and you need me write here and send the link to the issue on http://dallago.mtalk.net

Peace.
