### ISSUE TITLE
Crawling blacklist

### ISSUE THREAD

**Issue by julienschmidt** [Rostlab/JS16_ProjectD_Group4#33]
Here is a very incomplete list of names which are too generic / short / have a different meaning and therefore produce unusable results or just bloat the database (e.g. Will). I'd therefore like to blacklist them from the crawling by a simple attribute.
Please let me know if any of those persons is important.

```
Will
Will Humble
Willam
Yna
Zei
Quill
Rafe
Randa
Rigney
Rob
Robin
Roggo
Rolder
Rolfe
Rorge
Rosey
Rowan
Rudge
Rugen
Rus
Ryk
Sallor
Satin
Serra
Shella
Skinner
Squint
Squirrel
Tarle
Terro
Timon
Timeon
Timoth
Timett
Utt
Val
Violet
Wallen
Walton
Wate
Watt
Addam
Aggo
Albett
Alia
Alyn
Amabel
Armen
Arneld
Arnell
Arron
Bandy
Bannen
Barre
Barra
Bass
Barth
Becca
Beck
Bella
Ben
Benedict
Bennis
Biter
Boy
Brea
Brella
Brenett
Briar
Bryen
Bump
Buu
Byron
Cass
Carrot
Cerrick
Chiggen
Clement
Conn
Dake
Dalla
Dan
Del
Desmond
Dirk
Dobber
Dolf
Easy
Eggon
Elza
Fern
Ferret
Frenya
Gage
Galt
Gared
Garizon
Gariss
Gascoyne
Gavin
Gerren
Ghael
Gillam
Gilly
Grunt
Gulian
Hake
Hali
Halder
Haldon
Harra
Harwin
Helly
Henk
Hod
Hobb
Hoke
Holger
Holly
Hugh
Husband
Iggo
Jacks
Jayde
Kegs
Kurz
Kyle
Lanna
Leathers
Lem
Lenn
Lester
Lorren
Lothar
Lum
Maddy
Maggy
Mago
Malcolm
Maris
Matrice
Matt
Meg
Mela
Mord
Moro
Mullin
Mushroom
Myles
Nail
Nan
Nella
Nolla
Notch
Ogo
Ossy
Owen
Penny
Pia
Pudding
Qos
Quaro
```

**Comment by julienschmidt** [comment]
If you find more of such names, please let me also know ;)

**Comment by gyachdav** [comment]
here u go

> Reek
> Hodor

**Comment by julienschmidt** [comment]
> Reek
> Hodor

Removed

**Comment by gyachdav** [comment]
what? these two are the /important/ names. They should be kept. The /other short names/ should be removed.

**Comment by julienschmidt** [comment]
This is a blacklist. The /important/ names were removed from the blacklist and will therefore be available :wink:

**Comment by gyachdav** [comment]
got it. thx

**Comment by julienschmidt** [comment]
Reek is really causing trouble: https://twitter.com/search?f=tweets&vertical=default&q=reek&src=typd
We should think of other options, like including another keyword (`game`, `GoT`), to reduce the number of unwanted tweets.

**Comment by julienschmidt** [comment]
Isn't the "popular Reek" actually this guy: http://awoiaf.westeros.org/index.php/Theon_Greyjoy ?
I have no idea about GoT :stuck_out_tongue_closed_eyes:

**Comment by sacdallago** [comment]
I have no idea either.. @gyachdav ? :D Anyway yes, you have a black list, now you can try out a gray list where you change the original search term to something more restrictive.. Like your very wisely suggested "reek got"

**Comment by julienschmidt** [comment]
We might add a greylist and aliases later. For now we simple can not include too short / generic names.

I think in the end we actually have to use a whitelist. We might use a metric to approve certain names automatically, but whenever the DB gets updated with another name like "reek" we certainly run into problems.

It already takes about half a day to get the results with the REST API (only last ~7 days). The Mobile Crawler will not be much faster.. we simple can not waste hours on fetching thousands of useless tweets.

**Comment by sacdallago** [comment]
:+1: sure! Focus on what can be done

**Comment by gyachdav** [comment]
Okay not that important then.

**Comment by gyachdav** [comment]
Yes he is the same guy but with a changed persona and hence the new nick name. He is one of the characters that is set up for either greatness or utter failure. Either way the character will be quite important in the upcoming season and be called reek.  If you can filter the tweets to a manageable level for this character that would be great. Using the #got sounds reasonable.
