### ISSUE TITLE
Twitter Streaming API

### ISSUE THREAD

**Issue by julienschmidt** [Rostlab/JS16_ProjectD_Group4#46]
What is the current status of the Streaming API @santanumohanta ?
How does it have to be activated? Once or in Intervals?

**Comment by ghost** [comment]
@julienschmidt for streaming API we can pass maximum 400 kyewords to track in each stream...
In case we have 2000 character to track we need 5 streams!

**Comment by julienschmidt** [comment]
Or select just the most popular characters. For >90% of the characters the likelihood that we receive a tweet is... low.

**Comment by ghost** [comment]
@julienschmidt pushed the latest changes in my branch.

**Comment by ghost** [comment]
One pull request open for tweet stream save. added logic to stream tweets of popular characters and save them in db.

**Comment by julienschmidt** [comment]
Today is the feature freeze and there is still a lot of work missing to make the streaming API work properly.

It also interferes with the incremental updates of the mobile & REST API crawlers as they might abort too early when there are some new Tweets already in the DB.

We can include @santanumohanta  code (#83) as a basis for future work (like the REST API crawler which is also currently unused but there as a fallback) but we shouldn't invest more time to get it "production ready".
The existing crawlers might have some delay until the tweets pop up in our charts, but it works good enough.

With the current mobile crawler and its recently added caching (#84) we can reduce the delay to < 15 minutes. That should be good enough for now. And unlike with the REST API we can actually get all Tweets.

We should rather focus on getting better results from the data we already have. See the remaining open issues.

Yea or Nay, @santanumohanta @marcusnovotny  ?

**Comment by marcusnovotny** [comment]
I've successfully avoided dealing with the crawling mechanism so far _(yay)_, so my opinion is based on our current visualization. Since we're showing 1-hour-steps at most, a 15 minute delay is basically irrelevant. If we're down to that already, we should indeed focus on the sentiment calculation, which is still somewhat random.

**Comment by julienschmidt** [comment]
[Per default there is currently a pause of 1h between each incremental update](https://github.com/Rostlab/JS16_ProjectD_Group4/blob/develop/defaults.json#L19). But you could set it to 0s.

**Comment by ghost** [comment]
I agree @julienschmidt

**Comment by julienschmidt** [comment]
The API is frozen then!

**Comment by marcusnovotny** [comment]
:confetti_ball: :ghost: :tada:
