### ISSUE TITLE
[Twitter] Classify remaining characters

### ISSUE THREAD

**Issue by julienschmidt** [Rostlab/JS16_ProjectD_Group4#47]
Currently the crawler shows a list of "unclassified" characters at every start:

```
[crawler/blacklist][WARN] filtered unclassified: Willam
[crawler/blacklist][WARN] filtered unclassified: Willit
[crawler/blacklist][WARN] filtered unclassified: Willum
[crawler/blacklist][WARN] filtered unclassified: Wolmer
[crawler/blacklist][WARN] filtered unclassified: Wulfe
[crawler/blacklist][WARN] filtered unclassified: Wylla
...
```

Those are characters with names that are rather short and could possibly be "unsearchable" on Twitter.

Those remaining characters have to be classified into the whitelist and the blacklist (config.json[.sample]) like this:
1. Go to `https://twitter.com/search?f=tweets&vertical=default&q="{charactername}"&src=sprv`
2. If there are either not many tweets at all or at least half of the posts are about the GoT character, add it the the whitelist, otherwise add it to the blacklist.

**Comment by ghost** [comment]
If there are very less number of tweets available,like 10, which has more than 50% related to the character, should we keep it in white list?

**Comment by julienschmidt** [comment]
Yes. Only blacklist characters where there are too many unrelated posts.

**Comment by ghost** [comment]
ok

**Comment by ghost** [comment]
Unclassified character classified:-

## WHITELIST-

Sybassion
Cadwyl
Osmynd
Rhogoro
Rymolf  
Saathos 
Salloreon
Tuffleberry  
Tumberjon
Urrathon
Aethelmure
Alebelly
All-for-Joffrey
Argilac
Beldecar
Daeryssa
Draqaz
Esgred
Ezzelyno
Illifer 
Xhondo
Mordane
Orwyle
Melisandre
Patchface
Rhaego
Rakharo
Missandei
Wendamyr
Ygritte
Yoren
Quaithe
Rattleshirt
Alayaya
Anguy
Butterbumps
Clydas
Cohollo
Hodor
Urswyck
Varamyr
Qotho
Tormund
Polliver
Nymeria
Meribald
Timett
Pycelle
Gyldayn
Joramun
Ragwyle
Torwynd
Belwas
Bronn
Caleotte
Chiswyck
Dagmer
Doreah
Jhaqo
Jhiqui
Khrazz
Kurleket
Vyman
Murenmure
Nysterica
Toregg
Unella
Jyzene
Tagganaro
Tothmure
Tristimun
Ottomore
Quaro
Redtusk
S\'vrone
Sedgekins
Skittrick
Umfred
Aglantine
Agrivane
Allaquo
Ambrode
Anvil Ryn
Cetheres
Cossomo
Denestan
Dunaver
Fralegg
Harghaz
Harodon
Helliweg
Hibald
Hunnimore
Jhezane
Jorquen
Lennocks
Lormelle
Munciter
Yormwell
Zarabelo
Cragorn
Stonesnake
Ballabar
Bedwyck
Harmune
Murmison
Dhazzar
Gelmarr
Gynir
Kezmya
Larraq
Morgarth
Ollidor

## BLACKLISTED-

Cheyk
Tarber  
Todric
TomToo
Torrek
Borroq
Narbo
Narbert
Nightingale
Norjen
Norren
Nymos
Ocley
Orbelo  
Orivel
Poetess
Pollitor
Porridge
Praed
Puckens
Puddingfoot
Qalen
Quickfinger
Quort
Rawney
Redwyn
Reysen
Rigney
Roelle
Roggo
Rolder
Rolley
Roone
Runciter
Sallor
Sawwood
Sherrit
Shortear
Sloey
Softfoot
Stonehand
Turquin
Urreg
Vaellyn
Aethan
Arneld
Ayrmidon
Belandra
Belgrave
Beqqo
Bharbo
Brenett
Bryen
Cadwyn
Cerrick
Chiggen
Cutjack
Donyse
Erreck
Erreg
Frynne
Godwyn
Grazdan
Guyne
Gyles
Haggon
Hal (Hog)
Harra
Harsley
Hayhead
Helly
Heward
Holger
Husband
Ironbelly
Jaggot
Jayde
Jodge
Jommy
Jommo
Joseran
Jorgen
Joseth
Jurne
Kella
Kenned
Ketter
Kromm
Kyleg
Lamprey
Lanna
Lester
Lister
Lorcas
Lorimer
Lothar
Lucan
Lucos
Luton
Maddy
Malcolm
Malliard
Malleon
Mallor
Maris
Maslyn
Matrice
Maynard
Mebble
Melaquin
Meliana
Melicent
Mellei
Melly
Mellos
Meralyn
Miklaz
Mollander
Mollos
Moonshadow
Morra
Morrec
Murch
Myrtle
Werlag
Willam
Willit
Wolmer
Willum
Wylla
Yorkel
Ysilla
Zekko
Layna
Merry Meg
Myles
Oswyn
Orell
Rafford
Pypar
Othor
Shagga
Stygg
Mohor
Dennet
Groleo
Haldon
Hallyne
Harwin
Holly
Nettles
Timeon
Rorge
Marwyn
Senelle
Cellador
Zollo
Pylos
Shadrick
Tanselle
Monster
Azzak
Albett
Dalbridge
Desmond
Halder
Hop-Robin
Hullen
Jacks
Jeren
Jyana
Leathers
Marei
Mawney
Matthar
Mullin
Munda
Mysaria
Nella
Serala
Tallad
Todder
Tomard
Uller
Alfyn
Bloodbeard
Haggo
Harma
Hazzea
Jhogo
Kedry
Lomys
Marillion
Merrit
Krazz
Mikken
Aggar
Goady
Harbert
Kaeth
Lenyl
Lharys
Lorren
Maggy
Mezzara
Moelle
Morgil
Mully
Ordello
Palla
Porther
Qezza
Raynard
Scolera
Sigrin
Theomore
Tobbot
Vylarr
Urzen
Walgrave
Wulfe
