### ISSUE TITLE
[crawler] random hangs

### ISSUE THREAD

**Issue by julienschmidt** [Rostlab/JS16_ProjectD_Group4#51]
The crawler currently hangs randomly (?) sometimes without any exceptions for some reason after a long run time. To be debugged...

**Comment by julienschmidt** [comment]
I'm debugging with the following "alive ping" now. The `where` is updated before every larger block / at the beginning of each async code. Let's see where it hangs...

``` js
global.where = "main";

setInterval(function() {
    console.log("alive", global.where);
}, 30000);
```

**Comment by julienschmidt** [comment]
We have a winner:

```
[crawler/mobile][INFO] Lancel Lannister found: 100 inserted: 100 2015-09-11 11:00:06
alive mobile.get
alive mobile.get
alive mobile.get
alive mobile.get
alive mobile.get
alive mobile.get
...
```

I inserted that before the `request(..)` call in [crawler/mobile.js#L12](https://github.com/Rostlab/JS16_ProjectD_Group4/blob/cb8a588dfce9aee284c7d07077cd85a32bf7c871/crawler/mobile.js#L12). The callback gets never called. I already set a timeout of 30s in the request.

If you have any idea - let me know :disappointed:

**Comment by julienschmidt** [comment]
goddamnit github... "_might_ fix", not "fixes"

**Comment by julienschmidt** [comment]
#53 might have fixed the mobile.get hangs. But now [crawler/twitter.js#L34](https://github.com/Rostlab/JS16_ProjectD_Group4/blob/cb8a588dfce9aee284c7d07077cd85a32bf7c871/crawler/twitter.js#L34) is sporadically hanging. Try to use a custom Agent in the Twitter client too.

Selfnote: Twit already returns Promises, the callback->Promise wrapper can be removed

**Comment by sacdallago** [comment]
@marcusnovotny @santanumohanta what are you guys doing?

**Comment by marcusnovotny** [comment]
@sacdallago This issue exceeds my knowledge I'm afraid

**Comment by ghost** [comment]
@sacdallago  same for me ... this is over my head!

**Comment by sacdallago** [comment]
Good. At least make it clear to @julienschmidt and us :)
Btw I don't think @julienschmidt knows exactly where to look either but is trying something, _just saying_
And since I have you attention: please take care of closing @julienschmidt PR when he opens 'em

**Comment by julienschmidt** [comment]
The only way to change the behavior of the twitter client would be to change the global https.Agent - which would affect every other project when our package is included.

I therefore asked the developer of the Twit package to allow the usage of either keepAlive (which I assume "fixed" it for the mobile client) or a custom Agent. KeepAlive should also improve the performance again.

**Comment by julienschmidt** [comment]
Turns out there were exceptions for connections errors (connection reset etc) but those promises silently discard any exception if there is no `.catch(..)` handler...

**Comment by sacdallago** [comment]
So you are able to fix this? :) remember that between feature freeze and delivery you can fix bugs ;)

**Comment by julienschmidt** [comment]
See #66. I think it is fixed now.
KeepAlive would still be nice as it would speed up the crawler a bit since it avoids opening a new TCP connections and the TLS handshake for every single API request.

**Comment by julienschmidt** [comment]
To clarify, I think those hangs we're caused by reset connections which the Twitter servers seem to randomly do for whatever reason.
There were exceptions by the request package already, but since some of the Promises didn't have `.catch(..)` handlers, those exceptions were silently discarded instead of propagated (_ugh_, whoever was responsible for that specification must hate JS devs).
With this PR those exceptions are handled and the crawler makes up to a configurable number of retries.

**Comment by sacdallago** [comment]
This a very interesting finding! Who could be interested in this? Twitter? The developer of the Promises?

**Comment by julienschmidt** [comment]
Nobody. But there will be technical reasons for that (reset connections).

Regarding the promises: Someone sadistic.
