### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectD_Group4#59]
after executing `var d4 = require('gotsentimental');`

```
/home/yasar/Workspace/web/jsseminar/JS16_ProjectF/node_modules/gotsentimental/core/debug.js:10
        console.log("[\x1b[36m"+prefix+"\x1b[0m]", ...args);
                                                   ^^^

SyntaxError: Unexpected token ...
```

**Comment by julienschmidt** [comment]
That is valid (strict) ES6 JavaScript and works well with recent node.js versions. Time to update!

**Comment by julienschmidt** [comment]
That might not be the only code causing problems with old node.js versions btw. I made use of other ES6 features and especially excessive use of Promises.

**Comment by yashha** [comment]
Thanks :)
I love updating my node :heart:  :smile:

**Comment by sacdallago** [comment]
I love the _excessive_ @julienschmidt 
@yashha binaries are your friend! I don't know how to this day it is possible that package managers are so crappy
