### ISSUE TITLE
[visualization] change data on zoom

### ISSUE THREAD

**Issue by julienschmidt** [Rostlab/JS16_ProjectD_Group4#65]
The CSV "API" provides data for 3 zoom levels: year (contains data per day), month (per hour), day (per minute).

When reaching a certain zoom level the more specific data should be loaded and the graph replaced.
Maybe it is also necessary to load 2 files and append them when e.g. parts of 2 months are currently visible.

**Comment by marcusnovotny** [comment]
Will look into it this evening

**Comment by marcusnovotny** [comment]
Referencing the new API from #70 

> ```
> name.csv: overall file with values per day (of all years)
> name/2016-03.csv: monthly file with values per hour (of the given month)
> ```

However, my crawler is currently running, and in the name.csv there's only one value per month, not per day. Also, in the name/month.csv files there's only one single value for the month aswell. Am I missing something?

**Comment by julienschmidt** [comment]
#72 :beetle:

**Comment by marcusnovotny** [comment]
Doing the lord's work here.

**Comment by sacdallago** [comment]
@marcusnovotny did you say **Lorde**?
![](http://vignette2.wikia.nocookie.net/southpark/images/8/83/Lorde_AKA_Randy.png/revision/latest?cb=20141206231728)

**Comment by marcusnovotny** [comment]
Ya ya ya I am Lorde

**Comment by marcusnovotny** [comment]
Progress tracked over at #71
