### ISSUE TITLE
[meta] status report

### ISSUE THREAD

**Issue by julienschmidt** [Rostlab/JS16_ProjectD_Group4#67]
@marcusnovotny @santanumohanta what are you working on? I haven't seen any code from you in over a week. Our deadlines are approaching fast :wink: 

Status of my work: My mobile-site crawler should now work fine. The JS API should now also be more or less production-ready. I'm currently working on getting the aggregation (analyzing the tweets and write the CSV files) working. Expect a PR later. [This will also be the last thing I work on](https://rostlab.org/~gyachdav/js16/html/JS16_ProjectD_Group4.html).

**Comment by marcusnovotny** [comment]
@julienschmidt finishing the SEO action plan right now, then back to coding. You'll get a status update from me tonight. Have to get used to all the fancy new changes, it's pretty overwhelming from my limited newbie point of view I have to admit.

You should definitely get a break. You've contributed an awful lot to our project and I have mad respect for you work _tips fedora_. I think @santanumohanta and I should also write the report on our own given that you've worked a lot more than we did, what do you say?

**Comment by ghost** [comment]
@julienschmidt  The latest code, the level it has reached... it is very much complex/hard for me to work on...  As you know that previously I have already written code which will stream tweets for a query but it is really difficult for me to integrate it in latest existing code.

@marcusnovotny yes we can start writing the report. Lets discuss on it.

**Comment by julienschmidt** [comment]
@santanumohanta Basically the project is now a package without any "main file" anymore. See `example/app/app.js` for that. From there the exported functions (see `index.js`) of the package are called. All the twitter stuff is in `crawler/` and the database interaction still in `models/`.

Basically you would have to create another exported function in index.js for starting to listen to to stream. In that function you get a list of the most popular characters (API by Project A now has some sort of rank, we have `crawler/got` for easy interaction). With that you register the stream and insert new Tweets (see `crawler/tweets`, there is already a function for that). Probably you also have to match the tweet text against the character names again.

Otherwise: Figure it out... but do _something_. You haven't contributed much so far and didn't do much for the presentation either. See also the open issues, which are there so you start working on them!

**Comment by sacdallago** [comment]
I agree with @julienschmidt . Saying "_it's hard_" and just sitting there waiting for life to unfold is not an excuse in my opinion :)  
He just took care of explaining to you the main parts and I'm sure @julienschmidt would be happy to have you programming with him in the same room. You would understand something more and he would be able to take brakes and confront with someone at times.

**Comment by julienschmidt** [comment]
@sacdallago I think today, maybe tomorrow, is the last day I will work on this project for now. I have a thesis to write...

**Comment by marcusnovotny** [comment]
App is running, crawler is crawling #happyday
Still have the problem with the forever-lasting fetchEpisodes() call. Back to work tomorrow :runner:

**Comment by julienschmidt** [comment]
I just finished. A the first full crawl.
Then I updated episodes / characters from Project A. All `_id`s changed.
Now I have about 1 million tweets which can not be associated with a character  :weary:

**Comment by julienschmidt** [comment]
And see https://github.com/Rostlab/JS16_ProjectD_Group4/pull/70 there an episodes.csv is already generated :wink:

**Comment by marcusnovotny** [comment]
Will check #70 :raised_hands: 

Ouh shit. When did those change? Can I prevent that from happening? Started crawling ~2 hours ago, wanted to run it over night :smile:

**Comment by julienschmidt** [comment]
Maybe wait until the morning. I'll try to finish #70 before I go to sleep. Then the backend should be more or less complete (except that the analysis is still shit).
The full crawl took me ~14 hours btw :laughing:

**Comment by marcusnovotny** [comment]
Ok then let's crawl again tomorrow :sweat_smile: Good night & get some sleep!

Maybe it makes sense to finish the blacklist asap #47 ? For example, I noticed the mobile crawler spent 1-2 cycles crawling the character [Paxter Redwyne](http://awoiaf.westeros.org/index.php/Paxter_Redwyne) and I'm rather confident the tweets were from [this account @Paxter_Redwyne](https://twitter.com/search?src=typd&q=paxter%20redwyne) which has nothing to do with the show. Should save us some time. If you want I'll work on that tomorrow.

**Comment by julienschmidt** [comment]
After 553/1398 characters crawled, "Paxter Redwyne" is the most hated character :laughing: 

We should maybe make another "copycat" list, where we filter tweets by users with the same name. But I don't think we can avoid them during the search / crawling :worried: 

Btw, we're doing strict search, so these are the tweets we're crawling: https://twitter.com/search?f=tweets&vertical=default&q=%22paxter%20redwyne%22&src=sprv
(notice the quotation marks and the `src=sprv` instead of `src=typd`)

**Comment by julienschmidt** [comment]
And fixing the visualization and #42 should have the highest priority for now.

**Comment by ghost** [comment]
I have pushed in my branch Streaming for most popular character...now working on saving the tweets against character.
