### ISSUE TITLE
move API docs to the wiki

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectD_Group4#69]
keep install, usage etc in readme.

**Comment by julienschmidt** [comment]
uuhm why? It's common practice to put it into the README.md. This way it also shows up on https://www.npmjs.com/package/gotsentimental

And from a few years of GitHub experience: no one looks into the wiki (assuming you meant the repo wiki).

**Comment by gyachdav** [comment]
yup. well the motivation is to keep the readme short and sweet for users and the wiki for devs. you put a link the readme to the repo wiki in the "for devs" section. but if that means the api docs wont cary over to the npm package then forget what i said.
