### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by julienschmidt** [Rostlab/JS16_ProjectD_Group4#71]
- [x] Start on time-range with data. Prevent zooming / panning out of our data-range.
- [x] Mark episode airing dates on the x-axis
- [x] detect CSV path prefix (not always `/csv`, depends on the implementation) from original passed CSV path
- [x] Remove [monotone interpolation](https://github.com/Rostlab/JS16_ProjectD_Group4/blob/develop/public/chart.js#L31). Handle missing CSV values.
- [x] Define style with Project F.
- [x] Error message when no CSV is available (e.g. for blacklisted characters)
  - Error message is still thrown & displayed in console though
- [x] Horizontal scrollbar
- [x] Trendline / interpolated average of (pos-neg)
- [x] Simple legend
- [x] Compatibility across browsers: Flawless performance on Chrome 51, good performance on Firefox 45 & IE11
- [x] Zoom into monthly view with data per hour #65 (see pull request #110)
- [x] "stream" values: only insert / render elements for data that is (nearly) visible.

TODO
- [ ] Tool / Results explanation on About page, or: More sophisticated Legend with foreignObject

**Comment by marcusnovotny** [comment]
Thanks for the guidance!

**Comment by marcusnovotny** [comment]
I like the column chart idea, that would clean up the x-axis and make the results more transparent (seeing what the values exactly belong to).

 I'm just a little worried about the hourly view because the sentiment values are gonna be in the [-1;1] range for most of the characters

**Comment by julienschmidt** [comment]
![screen shot 2016-03-29 at 01 35 26](https://cloud.githubusercontent.com/assets/944947/14093504/9ab6786a-f54e-11e5-8f6c-4110ecd6a26e.png)

The graph needs to learn to accept boundaries!

**Comment by julienschmidt** [comment]
Maybe you should also communicate with Project F regarding styling. I think they will use a dark theme :wink:

**Comment by marcusnovotny** [comment]
What browser are you using? That is super weird. I'm not having this issue in Chrome. Just checked and Firefox does the same though, I'll look into it.

Good point, I'll summon one of them into this issue tomorrow :smile:

**Comment by julienschmidt** [comment]
Firefox 45.0.1 (OS X)

**Comment by marcusnovotny** [comment]
@julienschmidt @santanumohanta 

Just played around with interpolated average (positive score -  negative score) as a trendline and it looks horrible. 

Full scale graph
![](http://i.imgur.com/64nM41O.png)

Full scale graph + trendline
![](http://i.imgur.com/0CZzwpN.png)

Detailed graph season 5 + trendline
![](http://i.imgur.com/4fxjBM4.png)

Honestly, I'd just leave the whole trendline out. You can see how certain episodes affect the sentiment already as the graph is, since we're showing both the positive and the negative sentiment score. I can't think of another function we could put in that offers additional information. A regression analysis would be just as useless for example.

@gyachdav what are your thoughts on this, since estimating a trend is listed as a mandatory feature in the project description? Does Group D5's tool compensate for this because they seem to do more in-depth analysis for the current timeframe ([D5 #73](https://github.com/Rostlab/JS16_ProjectD_Group5/issues/73#issuecomment-203075215))?

**Comment by julienschmidt** [comment]
It also needs smoothing, not just interpolation

**Comment by marcusnovotny** [comment]
AFAIK there's no native D3 JS functionality to smoothen curves apart from the provided interpolators, so I'd have to write my own, right? I could aggregate weekly averages and plot a curve for them. I'll set something up, still questioning the usefulness though

**Comment by sacdallago** [comment]
1. To me, it actually is very informative. I can immediately grasp the feeling at that given time. I would though highlight the curve more, make it stick out more (bolder, thiker).
   
   **EDIT** Bolder, thiker when you zoom in, lighter when you zoom out. Sure, in the full timeline graph the tendency would me more interesting, while in the detailed one the curve that you propose is way more interesting
2. Why don't you use separate curves for the two data types? If you don't think this viz makes sense to you, try to break down the problem: Why don't you overlay on a different graph the two curves (one green, one red) with the same axes? Visually you immediately get if a character is liked more or less
3. What you are trying to show with this x polynomial interpolation is the more-positive, more-negative or neutral tendency at **a given time**. If on the other hand you want to build a tendency curve, you should try to fit simpler functions into your data, as for example a simple line. Then the points would highlight your error, but you would have a tendency, which is what I think is confusing you. This, though, as said in point 1. is very informing if you can read it right

**Comment by julienschmidt** [comment]
Maybe just use the average of the last 3 days each to smooth it.
We should then also explain somewhere (e.g. when hovering the curve) what we're visualizing with it.

**Comment by sacdallago** [comment]
@julienschmidt that would still not solve the problem for such a big dataset. You want to smooth over 3 days, but have a 5y datastore... So basically the curve would look a little bit smoother over 3 days, but you actually loose information and the best information that this curve can get you, like in the 3rd image posted.

If you really want to show a tendency, use simple curves! No need to smooth. Make a line fit trough the data. Not a polynomial function of order X.

**Comment by julienschmidt** [comment]
A line is too simple as I (without ever having watched a single episode) assume that characters can develop and turn from good to bad and vice versa

**Comment by sacdallago** [comment]
OK. :D Then find a _simple_ degree that represents the data, but not so high it fits it: ![](https://inkslwc.files.wordpress.com/2012/02/miprimary1.png) **if you want to show tendency**.
Again: the curve that you show now for me makes a lot of sense.
You are basically trying to ovoid overfitting.

**Comment by marcusnovotny** [comment]
For me the currently shown trend function just uselessly crowds the chart. The information you get from it is easily visible anyway, also in the 3rd picture.

Tendency was what I meant, but I'm not sure if I can still do it with two days to go. The other issues have higher priority

**Comment by sacdallago** [comment]
Did I mention that I like that curve anyway?
:laughing: :laughing: :laughing:

**Comment by marcusnovotny** [comment]
@gyachdav please help @sacdallago is being mean :confounded:

**Comment by sacdallago** [comment]
Byatch I was born mean
![](http://images5.fanpop.com/image/photos/30300000/Da-best-3-mean-girls-30385553-500-213.gif)

**Comment by marcusnovotny** [comment]
Current visualization badly shopped into the site

![](http://i.imgur.com/YAWlUhz.png)

**Comment by julienschmidt** [comment]
Right now 99% of the graph are grey. Shouldn't we zoom in a bit more by default?

**Comment by marcusnovotny** [comment]
I get you. Just wanted to show people how much data they actually can access right from the start, but you're right.

I'll try both 1.1.2013 (includes Season 3) and 1.1.2014 (includes Season 4) as startDates and today as the endDate

**Comment by julienschmidt** [comment]
Maybe some indication how much more data there is and where we are on the timeline would be nice - basically a horizontal scrollbar.

**Comment by julienschmidt** [comment]
Maybe look around the D3 examples again. I'm pretty sure there are already clever solutions.

**Comment by marcusnovotny** [comment]
Added. Would be really useful. This is gonna get tough though

**Comment by marcusnovotny** [comment]
Man I like the tool a lot. The graph for Walder Frey for example - the character is basically unimportant for the whole show, apart from one major "negative" event where he's partaking (Red Wedding, S03E09) and surprise, there's a giant spike. Only the negative score should be a lot higher I guess

**Comment by sacdallago** [comment]
@julienschmidt idea with the start-zoomed-in is good!
On the matter of the trendline, I think I got confused maybe by something: this trendline can be overlayed or hidden with some user input? Because then I understand when you say it's ugleyh. But if the user can decide whether to have it or not, then just keep it as you had it the other day, no other work needed ;)

Anyway, [_looking_ good](https://www.youtube.com/watch?v=LV9YjRiKGhs)

**Comment by marcusnovotny** [comment]
@julienschmidt Since you crossed the streaming stuff out: When would you think this is necessary? Would it not help our CPU performance? I'm worried it's too much because my browser is at 15-20% CPU usage when scrolling continually

**Comment by julienschmidt** [comment]
If we use an area chart we just have 2 SVG elements. The green area and the red area. Updating the coordinates of those areas would be even more expensive.

**Comment by marcusnovotny** [comment]
We also have the ~50 rectangles which represent the episodes, but I just removed them and it didn't seem to have an impact. How's it running on your machine? 

EDIT: I only notice zooming is **a lot** more fluent on Chrome compared to IE / Firefox

**Comment by julienschmidt** [comment]
Another ToDo: Error message when no CSV is available (e.g. for blacklisted characters)

**Comment by julienschmidt** [comment]
@marcusnovotny do you have a cool screenshot for the README?

**Comment by marcusnovotny** [comment]
I bet! Am not home yet, tomorrow around noon the latest

**Comment by marcusnovotny** [comment]
I'd like to use a complete Jon Snow csv. I have all the hourly values but not the daily (no idea how this happend). Do you have one?

**Comment by julienschmidt** [comment]
Found this zip file on my desktop. No idea how complete it is.
[Jon_Snow.zip](https://github.com/Rostlab/JS16_ProjectD_Group4/files/201263/Jon_Snow.zip)

**Comment by julienschmidt** [comment]
In the hourly view there is somehow almost no discussion during the episodes, but it spikes in the hour after the episodes. Is there maybe a shift problem?

**Comment by marcusnovotny** [comment]
Well, the episodes are gonna air pretty late so it should be near the end, but you're right it's strange at the moment. Maybe it's a time zone thing? I think the graph uses middle european time

**Comment by julienschmidt** [comment]
The data is in UTC

**Comment by marcusnovotny** [comment]
![](https://safcecblog.files.wordpress.com/2014/10/timeforchange.jpg)

**Comment by julienschmidt** [comment]
https://github.com/mbostock/d3/wiki/Time-Scales#utc

**Comment by marcusnovotny** [comment]
Just to get this right. I checked the Jon Snow csv & the huge spike after the last episode is at 2AM:

> 2015-06-15T02,1215,3105

Right now, the graph aligns with the data and displays the spike at 2AM. If I set the scale to UTC it shifts the graph two hours in the past to 12AM. Is the data intended to be used like that?

**Comment by julienschmidt** [comment]
I have no idea how D3 transforms / labels the data and what the default time zone is. I can only tell you that the data in the CSV is in UTC.

**Comment by marcusnovotny** [comment]
But then it should be correct already. The graph display the data as in the csv. If there's a shift it must have occured earlier?

**Comment by julienschmidt** [comment]
The episodes are shifted -1 day. E.g. April 20 9pm EST is already April 21 in UTC

**Comment by julienschmidt** [comment]
Should we just assume that every episode airs at 9pm EST and has the same runtime? Everything else is quite confusing.

**Comment by marcusnovotny** [comment]
Let's stick to the Jon Snow example. Episodes csv correctly states airing date is on [14th June](https://en.wikipedia.org/wiki/List_of_Game_of_Thrones_episodes#ep50) and is displayed 14-15th in the graph

> 2015-06-14,S05E10,"Mother's Mercy"

Jon Snow csv mentions spike at 2AM on the 15th. Graph displays it at exactly that time

> 2015-06-15T02,1215,3105

![](http://i.imgur.com/CBZBGJ3.png)

So it's all displayed just like in the data. If anything we should prepone the tweet times, I think they're a few hours late currently. The spike must have occured before 2AM the day after the airing.

Or am I missing something?

**Comment by julienschmidt** [comment]
> date is on 14th June and is displayed 14-15th in the graph

counter-intuitive, but now it highlights June 14th and stops at midnight. However the episode aired at June 15th 2am UTC I think.

**Comment by julienschmidt** [comment]
Ideally all the calculations would be in UTC, but he axis legend in the browser's local time.

**Comment by marcusnovotny** [comment]
Ah ok. I think I get it now. [www.episodate.com](https://www.episodate.com/tv-show/game-of-thrones?season=5) suggests that all seasons aired at 3AM CEST, so 1AM UTC. Spike makes sense then since he died at the very end of the episode.

I can make the episode bars less wide and set them to the right time, no problem. 

I think it makes most sense to use Eastern Time [(just like HBO)](http://www.hbo.com/search?type=schedule&seriesIds=PMRS1663&q=GAME%2BOF%2BTHRONES) for all users though, so the episodes air at 9PM. Those 2AM spikes look weird, it's more convenient not to think about time conversions imo.

**Comment by julienschmidt** [comment]
And it isn't a trend line. More like an average curve.

**Comment by julienschmidt** [comment]
And while I'm already nitpicking: Score / Hour is not a button and therefore shouldn't look like one

**Comment by julienschmidt** [comment]
aaand the scrollbar is too slow. It should always be directly under the cursor.

**Comment by marcusnovotny** [comment]
Okay, that's gonna take a little more time (mostly the Date thing) and I'm super busy today & tomorrow. I'll fix it until Tuesday.

**Comment by julienschmidt** [comment]
No rush, it's completely up to you. The official part of the project is over anyway

**Comment by marcusnovotny** [comment]
Another issue: there's no way to scroll back out again if you're using a touchpad without multitouch, eg. Notebook without mouse. Probably need zooming buttons.

Edit: Picture delayed until Date is fixed

**Comment by gyachdav** [comment]
I loooove it!! thanks @sacdallago @marcusnovotny and @julienschmidt for setting it up!

How come http://csv.got.show/ only shows a bunch of minor characters and only has 320855 tweets? Are you refilling the db?

**Comment by julienschmidt** [comment]
@gyachdav yes. It should take about 16 hours until all characters are crawled.

**Comment by marcusnovotny** [comment]
This is taking over hand here, I'll open up a new issues for bug fixes :wink:
