### ISSUE TITLE
Partly missing tweet history

### ISSUE THREAD

**Issue by marcusnovotny** [Rostlab/JS16_ProjectD_Group4#78]
For most of our main characters, the tweet history goes back all the way until 2011-2010. However, I noticed that for some of them we only have data from mid / end 2014 on (Daenerys Targaryen, Sansa Stark) or even later (Tyrion Lannister starts in August 2015), even though those characters were already important before. The history also looks cut off unnaturally. What could prevent the crawler from getting those older tweets?

**Comment by julienschmidt** [comment]
The twitter history for those queries ends there, it shows "no more tweets". We can still get those posts with a different search query (e.g. https://mobile.twitter.com/search?q=%22Jon%20Snow%22%20until%3A2016-03-08&src=typd ).
I'm working on the implementation.

**Comment by julienschmidt** [comment]
```
...
[crawler/mobile] Jon Snow found: 100 inserted: 4 2016-01-29 11:49:03
[crawler/mobile] Jon Snow found: 100 inserted: 4 2016-01-29 01:44:17
[crawler/mobile] History ended. Retry with new query: "Jon Snow" until:2016-01-29&s=sprv
[crawler/mobile] History ended. Retry with new query: "Jon Snow" until:2016-01-29&s=sprv
[crawler/mobile] Jon Snow found: 100 inserted: 0 2016-01-28 22:29:37
[crawler/mobile] History ended. Retry with new query: "Jon Snow" until:2016-01-28&s=sprv
[crawler/mobile] Jon Snow found: 84 inserted: 0 2016-01-28 21:09:52
[crawler/mobile] Jon Snow found: 100 inserted: 0 2016-01-28 21:09:52
[crawler/mobile] Jon Snow found: 100 inserted: 6 2016-01-27 22:16:50
[crawler/mobile] Jon Snow found: 100 inserted: 4 2016-01-27 20:21:58
[crawler/mobile] Jon Snow found: 100 inserted: 7 2016-01-27 18:32:36
[crawler/mobile] Jon Snow found: 100 inserted: 1 2016-01-27 17:30:04
[crawler/mobile] History ended. Retry with new query: "Jon Snow" until:2016-01-27&s=sprv
[crawler/mobile] Jon Snow found: 100 inserted: 1 2016-01-27 15:45:07
[crawler/mobile] Jon Snow found: 100 inserted: 0 2016-01-26 23:36:05
...
```

I really have no idea what twitter is doing there. I assume it has technical reasons (caches etc).

But after working with Twitter for a while now: Twitter seems almost as broken as JavaScript. Random wrong Compression Headers, closed connections etc.

**Comment by sacdallago** [comment]
Free stuff is _never_ free of hassle
