### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by julienschmidt** [Rostlab/JS16_ProjectD_Group4#89]
After #81 we have a new problem: for some characters (e.g. Jon Snow, ~800.000 tweets) not all tweets fit into memory, which is currently necessary for the aggregation / generation of the CSV files:

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
[1]    34838 abort      node app
```

Any idea except working in chunks (which would complicate the aggregation a lot)?

@sacdallago @gyachdav

**Comment by gyachdav** [comment]
@julienschmidt can you explain the problem in further details? 

Is your node instance collapsing because you're storing all tweets in memory? it will help a lot to understand what data you're storing and why.

**Comment by gyachdav** [comment]
Do you really need all meta data for each tweet?

**Comment by julienschmidt** [comment]
We only save the text, the unique ID of the Tweet, the character this tweet belongs to, the tweet date and retweeted / favorited count. I think we need all of those.

Node crashes here when it tries to pull all the tweets (~800.000 in case of Jon Snow) out of the DB to run the aggregation:
https://github.com/Rostlab/JS16_ProjectD_Group4/blob/0fcb21290ca5329f4e8549a3ef5c1a5173f110da/aggregator/aggregator.js#L96

My current idea is to load just chunks (maybe up to 100.000 Tweets each) and process them after each other. But that probably complicates the logic quite a lot.

**Comment by gyachdav** [comment]
check out http://google.github.io/flatbuffers/

**Comment by gyachdav** [comment]
btw, you dont need to save the name 800k times

**Comment by gyachdav** [comment]
so If you alter your db schema to have all jonsnow tweets contained in a single jonsnow document you would be able to skip the find operation.

**Comment by julienschmidt** [comment]
Saving 800k embedded documents is a pretty bad idea.

**Comment by gyachdav** [comment]
all you need to save are refs not the docs

**Comment by julienschmidt** [comment]
You mean an array of Tweet IDs?

**Comment by gyachdav** [comment]
Well this really depends on what you do:
1. If you manage your own DB of tweets then you just store an array of internal IDs. You basically maintain your own index. But the advantage here is that you avoid the find operation. And you can presort your data. 
2. If tweeter is your primary data host then use tweet IDs. 

Afaik your situation fits the first scenario. Right?

**Comment by julienschmidt** [comment]
Yes we have our own DB with Tweets.
1. Is impractical since we then need some sort of JOIN in order to avoid reading every single Tweet on it's own. 
   For that we need MongoDB 3.2+ and the aggregation pipeline. I'm not how sure how well it performs:
   https://www.mongodb.com/blog/post/joins-and-other-aggregation-enhancements-coming-in-mongodb-3-2-part-1-of-3-introduction

Even then we still need some sort of chunking. Just reducing the size by a few bytes doesn't solve problem.

For now we could also replace the Character._id with just an integer.
The find and sort are not the bottleneck. We use indices for both.

**Comment by gyachdav** [comment]
why would you need a join? you have the IDs so all you need to do then is db.collection.find({_id:your_id})

at any rate, you should really ask yourself why are you trying to load all 800k tweets onto memory? this is the root of your problem.

**Comment by julienschmidt** [comment]
We don't want to do `db.collection.find({_id:your_id})` for 800k tweets either, especially with a remote DB.

So we're back at processing chunks.

**Comment by gyachdav** [comment]
well i haven't really heard a strong argument for processing all at once..

**Comment by julienschmidt** [comment]
performance

**Comment by julienschmidt** [comment]
And we're talking about seconds vs hours

**Comment by gyachdav** [comment]
how about using an in-memory key-value store? this would run outside your node allocated memory stack

**Comment by julienschmidt** [comment]
The problem is that we have very limited options on Heroku and also very limited RAM.

I'll now try to implement chunking somehow.

**Comment by gyachdav** [comment]
how much memory do 800k tweets take?

**Comment by julienschmidt** [comment]
About 150 MB I think. But we don't have a KV-store available on Heroku unless we buy an Add-On.

And it also doesn't solve the problem. Then we have the Tweets just in another DB. We could also just cache a chunk directly in node.

**Comment by julienschmidt** [comment]
Fixed in #91 using a streaming interface :tada:

**Comment by sacdallago** [comment]
Sorry, I got around this issue only now.
- [Redis](http://redis.io) might have been an option
- Maybe multithreading would have been an option
- Adjusting the node process available ram is _possible_

Why are you so worried about Heroku? We won't, in the end, service the site there ;) we have a 8 core, 16gig machine ready to be treated dirty:

``` bash
top - 17:55:18 up 14 days,  2:01,  2 users,  load average: 0.00, 0.01, 0.05
Tasks: 151 total,   1 running, 150 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:  16432676 total,  2528752 used, 13903924 free,   237576 buffers
KiB Swap: 16774140 total,        0 used, 16774140 free.  1604244 cached Mem
```

**Comment by julienschmidt** [comment]
Well.. now our package is already Cloud™ ready :laughing: 
We do the aggregation of the previous character while we crawl the data for the next character. The crawling is already slower and we can't speed it up since Twitter runs rate-limiting for their regular websites too.
So currently there is no need to optimize it any further.

But it's good to know that our database won't be limited to the 500 MB on M-Lab, I was a bit worried about that :+1:

**Comment by julienschmidt** [comment]
And yes, Redis is generally a saner option than MongoDB. I've worked with it before.
At least I can now tell that I actually worked with MongoDB before [when I bash it the next time](https://www.youtube.com/watch?v=b2F-DItXtZs) :wink:

**Comment by sacdallago** [comment]
:D Ouh.. we will still be working with mongolab for the time being :P but when the moment will come, we can have a db of max 10gigs
I know, it's not much.. but > 500 mb

**Comment by julienschmidt** [comment]
MongoDB states the current DB size at ~300 MiB. I guess there is enough space for a couple more weeks. However we're currently only querying 1398 of the > 2000 characters :wink:

**Comment by sacdallago** [comment]
I get it, I get it :D
