### ISSUE TITLE
Special characters in character slug

### ISSUE THREAD

**Issue by marcusnovotny** [Rostlab/JS16_ProjectD_Group4#90]
Stumbled upon [this guy](https://got-stats.herokuapp.com/characters/Jaqen%20H'ghar) in our dataset and noticed the route does not work with special characters like ' at the moment.

[http://localhost:1337/Jaqen_H'ghar](http://localhost:1337/Jaqen_H'ghar)

**Comment by julienschmidt** [comment]
That's a problem of Project A. We use the slugs they provide.

**Comment by julienschmidt** [comment]
https://got-api.bruck.me/api/characters/byId/56f5c296be62dc6e12808a60

**Comment by marcusnovotny** [comment]
I'll mention this issue over there then :)

**Comment by marcusnovotny** [comment]
Project A closed the issue, let's see how it works in the next crawl

**Comment by marcusnovotny** [comment]
[The API has changed](https://api.got.show/api/characters/Jaqen%20H'ghar) but we're still using the old slug. How do we update it? The character is among the most discussed and therefore pretty important

**Comment by julienschmidt** [comment]
Delete the character from the characters collection in the DB (type `mongo` in the shell for the shell client. Then type `help` for further help :wink: ). On the next update the crawler will insert the Character with the new slug again.

**Comment by marcusnovotny** [comment]
Thanks, it worked!
