### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by julienschmidt** [Rostlab/JS16_ProjectD_Group4#96]
- 5 pages
- write up mostly about topic (references)
- basically translating slides into text

**Last page about project:**
- [x] discussion about challenges that we faced
- [x] who did what?
- [x] include final slides
- [x] references pages

**Deadline: 2016-04-15**

**Comment by marcusnovotny** [comment]
Since we can only select one assignee here: Will be handled by @santanumohanta and myself

**Comment by marcusnovotny** [comment]
Hey @santanumohanta! I'm still working on Visualization & Landing Pages this week and will be pretty busy early next week too. Could you already start with the report?

**Comment by ghost** [comment]
@marcusnovotny yes, sure.

**Comment by marcusnovotny** [comment]
@santanumohanta I won't be able to contribute before Tuesday. Could you tell us what you already have & what you are going to need?

I think @julienschmidt has to write the part about his contribution himself (from the guidelines: "1 page about your project [...] provide description of the project and **tell who did what**", so only a few lines), but we'll take care of the rest :)

**Comment by marcusnovotny** [comment]
... And we could do this instead. I volunteer

> Also about reports - we’re giving you the option to NOT write the 5th page of the report but INSTEAD you can just write some short, really cool and simple (one that the old couple living next door could understand) description of what you did in your project. Send it to us (do NOT post from your private accounts) and we will post it on the social media pages.  Each post need to contain a website screenshot and the hashtag #GoTShow!

**Comment by ghost** [comment]
@marcusnovotny I will give an update by tonight.

**Comment by ghost** [comment]
I have done the report and sent it by mail to you @marcusnovotny @julienschmidt .

**Comment by ghost** [comment]
report submitted !
