### ISSUE TITLE
Need for a menu / legend?

### ISSUE THREAD

**Issue by marcusnovotny** [Rostlab/JS16_ProjectD_Group4#97]
Will we need a user menu for our application? My guess right now is no, because looking at the current website, our tool will only be shown on the [character pages](https://got-stats.herokuapp.com/characters/Arya%20Stark), so we don't even need navigation.

A legend explaining the chart elements definitely seems necessary though. Could be integrated as a pop up box or just plain Text below our Tool on the Character page (definitely easiest).

Any thoughts on this? How is Group 5 handling this @kajo404 @jonny3576 @Logarythms ?

**Comment by julienschmidt** [comment]
Ask group F how they plan to integrate it.

**Comment by jonny3576** [comment]
I think that a pop up box would be very interesting.
At the moment Group 5 won't do any Visualization so this would be delegated to Project F.
**BUT** maybe they can write the information-text? 
This has clearly not the highest priority as the Twitter-application isn't working at the moment.
@kajo404 @Logarythms @vanp33 please tell us here if you think the suggestion is at least doable till April 1st.
If so I will connect with Project F.

**Comment by marcusnovotny** [comment]
Had a [nice chitchat](https://github.com/Rostlab/JS16_ProjectF/issues/200), Visualization goals updated #71
