### ISSUE TITLE
Need for recrawl after host replacement?

### ISSUE THREAD

**Issue by marcusnovotny** [Rostlab/JS16_ProjectD_Group4#99]
Just tried replacing the host in our config files since the bruck db has now migrated to "api.got.show". After starting the crawler, it gave me a MongoError E11000 for duplicate keys, referring to the character slug. It works after switching to a new db and I'm currently recrawling - Just wanted to ask if that's necessary or if there's a workaround which allows us to keep the old db.

**Comment by julienschmidt** [comment]
Probably you could insert back the tweets from one DB into the other, e.g. using the shell client (mongo). But don't ask me how :P

**Comment by marcusnovotny** [comment]
Yeah in that case my crawler's gonna have a sleepless night again. Issue closed :smile:

Currently uploading my latest csv data in case anyone needs it for testing, I'll edit the link in here later @santanumohanta 

[csv safe](https://drive.google.com/file/d/0B7sZl-d6L1--Q3VLM25LTE9ndm8/view?usp=sharing)

**Comment by sacdallago** [comment]
? Where the tweets stored on the same mlab instance as A was using? I can give you access to the mlab instance I'm using now (I took an empty one and started off zero).
This are precisely the reasons why I did this, for things to go wrong :D Can you elaborate on what you did, what should be done when moving server/db,...?

**Comment by julienschmidt** [comment]
No, we are using local instances. Project F is currently using a second mlab instance since they can not create a local instance on Heroku.

**Comment by julienschmidt** [comment]
But the problem is that our data is bound to the character `_id`s

**Comment by sacdallago** [comment]
Seriously? :D
You should use the char name or slug, definitely, definitely, not the `_id`.. I thought I had stressed this out already like a million times :laughing:

**Comment by julienschmidt** [comment]
Yes we adhered to the usual database design principles and used foreign keys instead of random strings. Maybe a bit too foreign... :stuck_out_tongue_winking_eye: 

Well the API is frozen now.

**Comment by sacdallago** [comment]
Forzen like [**_Let it go, let it go_**](https://youtu.be/CYsrV3zGd0c?t=59s)? What do you mean with frozen?

**Comment by julienschmidt** [comment]
I mean frozen as in the past participle of "freeze" - as in "feature freeze".

And to be fair, our DB schema already existed when `_id` was still the only unique attribute in Project A's Schema.

**Comment by sacdallago** [comment]
FF long doesn't mean you don't need to touch the code anymore :laughing: it's testing, getting rid of bugs and cleaning up. This one is very, very close to the _cleaning up_ side of life ;) I don't see any functionality changing?
